// Code generated by MockGen. DO NOT EDIT.
// Source: dynamo_global_index_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	djoemo "github.com/adjoeio/djoemo"
	prometheus "github.com/prometheus/client_golang/prometheus"
	"go.uber.org/mock/gomock"
)

// MockGlobalIndexInterface is a mock of GlobalIndexInterface interface.
type MockGlobalIndexInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGlobalIndexInterfaceMockRecorder
}

// MockGlobalIndexInterfaceMockRecorder is the mock recorder for MockGlobalIndexInterface.
type MockGlobalIndexInterfaceMockRecorder struct {
	mock *MockGlobalIndexInterface
}

// NewMockGlobalIndexInterface creates a new mock instance.
func NewMockGlobalIndexInterface(ctrl *gomock.Controller) *MockGlobalIndexInterface {
	mock := &MockGlobalIndexInterface{ctrl: ctrl}
	mock.recorder = &MockGlobalIndexInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGlobalIndexInterface) EXPECT() *MockGlobalIndexInterfaceMockRecorder {
	return m.recorder
}

// GetItemWithContext mocks base method.
func (m *MockGlobalIndexInterface) GetItemWithContext(ctx context.Context, key djoemo.KeyInterface, item interface{}) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemWithContext", ctx, key, item)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemWithContext indicates an expected call of GetItemWithContext.
func (mr *MockGlobalIndexInterfaceMockRecorder) GetItemWithContext(ctx, key, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemWithContext", reflect.TypeOf((*MockGlobalIndexInterface)(nil).GetItemWithContext), ctx, key, item)
}

// GetItemsWithContext mocks base method.
func (m *MockGlobalIndexInterface) GetItemsWithContext(ctx context.Context, key djoemo.KeyInterface, items interface{}) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemsWithContext", ctx, key, items)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsWithContext indicates an expected call of GetItemsWithContext.
func (mr *MockGlobalIndexInterfaceMockRecorder) GetItemsWithContext(ctx, key, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsWithContext", reflect.TypeOf((*MockGlobalIndexInterface)(nil).GetItemsWithContext), ctx, key, items)
}

// GetItemsWithRangeWithContext mocks base method.
func (m *MockGlobalIndexInterface) GetItemsWithRangeWithContext(ctx context.Context, key djoemo.KeyInterface, items interface{}) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemsWithRangeWithContext", ctx, key, items)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsWithRangeWithContext indicates an expected call of GetItemsWithRangeWithContext.
func (mr *MockGlobalIndexInterfaceMockRecorder) GetItemsWithRangeWithContext(ctx, key, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsWithRangeWithContext", reflect.TypeOf((*MockGlobalIndexInterface)(nil).GetItemsWithRangeWithContext), ctx, key, items)
}

// QueryWithContext mocks base method.
func (m *MockGlobalIndexInterface) QueryWithContext(ctx context.Context, query djoemo.QueryInterface, item interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryWithContext", ctx, query, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryWithContext indicates an expected call of QueryWithContext.
func (mr *MockGlobalIndexInterfaceMockRecorder) QueryWithContext(ctx, query, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWithContext", reflect.TypeOf((*MockGlobalIndexInterface)(nil).QueryWithContext), ctx, query, item)
}

// WithLog mocks base method.
func (m *MockGlobalIndexInterface) WithLog(log djoemo.LogInterface) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithLog", log)
}

// WithLog indicates an expected call of WithLog.
func (mr *MockGlobalIndexInterfaceMockRecorder) WithLog(log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithLog", reflect.TypeOf((*MockGlobalIndexInterface)(nil).WithLog), log)
}

// WithMetrics mocks base method.
func (m *MockGlobalIndexInterface) WithMetrics(metricsInterface djoemo.MetricsInterface) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithMetrics", metricsInterface)
}

// WithMetrics indicates an expected call of WithMetrics.
func (mr *MockGlobalIndexInterfaceMockRecorder) WithMetrics(metricsInterface interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithMetrics", reflect.TypeOf((*MockGlobalIndexInterface)(nil).WithMetrics), metricsInterface)
}

// WithPrometheusMetrics mocks base method.
func (m *MockGlobalIndexInterface) WithPrometheusMetrics(registry *prometheus.Registry) djoemo.GlobalIndexInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithPrometheusMetrics", registry)
	ret0, _ := ret[0].(djoemo.GlobalIndexInterface)
	return ret0
}

// WithPrometheusMetrics indicates an expected call of WithPrometheusMetrics.
func (mr *MockGlobalIndexInterfaceMockRecorder) WithPrometheusMetrics(registry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithPrometheusMetrics", reflect.TypeOf((*MockGlobalIndexInterface)(nil).WithPrometheusMetrics), registry)
}
