// Code generated by MockGen. DO NOT EDIT.
// Source: dynamo_global_index_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	djoemo "github.com/adjoeio/djoemo"
	gomock "github.com/golang/mock/gomock"
)

// MockGlobalIndexInterface is a mock of GlobalIndexInterface interface.
type MockGlobalIndexInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGlobalIndexInterfaceMockRecorder
}

// MockGlobalIndexInterfaceMockRecorder is the mock recorder for MockGlobalIndexInterface.
type MockGlobalIndexInterfaceMockRecorder struct {
	mock *MockGlobalIndexInterface
}

// NewMockGlobalIndexInterface creates a new mock instance.
func NewMockGlobalIndexInterface(ctrl *gomock.Controller) *MockGlobalIndexInterface {
	mock := &MockGlobalIndexInterface{ctrl: ctrl}
	mock.recorder = &MockGlobalIndexInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGlobalIndexInterface) EXPECT() *MockGlobalIndexInterfaceMockRecorder {
	return m.recorder
}

// GetItem mocks base method.
func (m *MockGlobalIndexInterface) GetItem(key djoemo.KeyInterface, item interface{}) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", key, item)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockGlobalIndexInterfaceMockRecorder) GetItem(key, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockGlobalIndexInterface)(nil).GetItem), key, item)
}

// GetItemWithContext mocks base method.
func (m *MockGlobalIndexInterface) GetItemWithContext(ctx context.Context, key djoemo.KeyInterface, item interface{}) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemWithContext", ctx, key, item)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemWithContext indicates an expected call of GetItemWithContext.
func (mr *MockGlobalIndexInterfaceMockRecorder) GetItemWithContext(ctx, key, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemWithContext", reflect.TypeOf((*MockGlobalIndexInterface)(nil).GetItemWithContext), ctx, key, item)
}

// GetItems mocks base method.
func (m *MockGlobalIndexInterface) GetItems(key djoemo.KeyInterface, items interface{}) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItems", key, items)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockGlobalIndexInterfaceMockRecorder) GetItems(key, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockGlobalIndexInterface)(nil).GetItems), key, items)
}

// GetItemsIteratorWithContext mocks base method.
func (m *MockGlobalIndexInterface) GetItemsIteratorWithContext(ctx context.Context, key djoemo.KeyInterface, searchLimit int64) (djoemo.IteratorInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemsIteratorWithContext", ctx, key, searchLimit)
	ret0, _ := ret[0].(djoemo.IteratorInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsIteratorWithContext indicates an expected call of GetItemsIteratorWithContext.
func (mr *MockGlobalIndexInterfaceMockRecorder) GetItemsIteratorWithContext(ctx, key, searchLimit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsIteratorWithContext", reflect.TypeOf((*MockGlobalIndexInterface)(nil).GetItemsIteratorWithContext), ctx, key, searchLimit)
}

// GetItemsWithContext mocks base method.
func (m *MockGlobalIndexInterface) GetItemsWithContext(ctx context.Context, key djoemo.KeyInterface, items interface{}) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemsWithContext", ctx, key, items)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsWithContext indicates an expected call of GetItemsWithContext.
func (mr *MockGlobalIndexInterfaceMockRecorder) GetItemsWithContext(ctx, key, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsWithContext", reflect.TypeOf((*MockGlobalIndexInterface)(nil).GetItemsWithContext), ctx, key, items)
}

// GetItemsWithRangeWithContext mocks base method.
func (m *MockGlobalIndexInterface) GetItemsWithRangeWithContext(ctx context.Context, key djoemo.KeyInterface, items interface{}) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemsWithRangeWithContext", ctx, key, items)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsWithRangeWithContext indicates an expected call of GetItemsWithRangeWithContext.
func (mr *MockGlobalIndexInterfaceMockRecorder) GetItemsWithRangeWithContext(ctx, key, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsWithRangeWithContext", reflect.TypeOf((*MockGlobalIndexInterface)(nil).GetItemsWithRangeWithContext), ctx, key, items)
}

// Query mocks base method.
func (m *MockGlobalIndexInterface) Query(query djoemo.QueryInterface, item interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", query, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Query indicates an expected call of Query.
func (mr *MockGlobalIndexInterfaceMockRecorder) Query(query, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockGlobalIndexInterface)(nil).Query), query, item)
}

// QueryWithContext mocks base method.
func (m *MockGlobalIndexInterface) QueryWithContext(ctx context.Context, query djoemo.QueryInterface, item interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryWithContext", ctx, query, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryWithContext indicates an expected call of QueryWithContext.
func (mr *MockGlobalIndexInterfaceMockRecorder) QueryWithContext(ctx, query, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWithContext", reflect.TypeOf((*MockGlobalIndexInterface)(nil).QueryWithContext), ctx, query, item)
}
